version: '3'
services:
    node:
        build: .docker/node
        volumes:
            - .:/var/www/yousign
        command: bash -c "yarn install && yarn build"

    maildev:
        image: djfarrelly/maildev
        container_name: yousign_maildev
        ports:
            - 25:25
            - 1080:80
        links:
            - rabbitmq

    rabbitmq:
        build: .docker/rabbitmq
        hostname: rabbit-node-1
        ports:
            - 60005:15672
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin

    apache:
        build: .docker/apache
        container_name: yousign_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/var/www/yousign
        depends_on:
          - php

    db:
        image: mysql:5.7
        container_name: yousign_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: yousign
            MYSQL_DATABASE: yousign
            MYSQL_USER: yousign
            MYSQL_PASSWORD: yousign
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        depends_on:
             - db

    php:
        build: .docker/php
        container_name: yousign_php
        ports:
            - "9000:9001"
        volumes:
            - .:/var/www/yousign:cached
        environment:
            - maildev_host=yousign_maildev
        links:
            - maildev
        depends_on:
            - maildev
            - db